language: python

branches:
  except:
  - gh-pages

stages:
- test

jobs:
  include:
  - python: 3.6
    env: TOXENV=unit_py3_6,check,doc
  - python: 2.7
    env: TOXENV=unit_py2_7,check,doc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y git
- sudo apt-get install -y xsltproc
- sudo apt-get install -y genisoimage
- sudo apt-get install -y enchant
- sudo apt-get install -y shellcheck

install:
- pip install --upgrade pip
- pip install tox

script:
- tox "-n $(nproc)"
